### ISSUE TITLE
Budget - Add category search

### ISSUE THREAD

**Issue by rubybeaches** [rubybeaches/BetterBudgetBuilds#25]
I adjusted the search to be in place and not absolute. I kind of like this for now - but when it scrolls the input scrolls out of view too.

I think I should make the scrollable drop down selections a separate div layer that appears and scrolls outside of the input, this would also allow me to revert it back to absolute if I want to.

Also make the scroll bar visible, but cuter

**Comment by youngchingjui** [comment]
Hi @rubybeaches , 

I used my tool [Issue To PR](https://issutopr.dev) to generate a [plan](https://issuetopr.dev/rubybeaches/BetterBudgetBuilds/issues/25) for this issue. IssueToPR uses AI agents to review your codebase and generate a plan. These are especially helpful when pasting into agent-assisted coding tools like Cursor.

Let me know if you find this useful - I can generate Plans for your other issues too, free of charge. 

---

# The Plan

## Issue Diagnosis
- The category search dropdown scrolls with the input because it is inline and statically positioned.
- The scrollbar is hidden and not stylized.

## Fix Plan
- Split the dropdown into an absolutely positioned, anchored, floating list.
- Add a visible and styled scrollbar.
- Refine styles/JSX for clean, bug-free dropdown UX (scroll, close, outside click, etc).

## Detailed Findings

### AddCategory.tsx (Relevant Parts)

- The search bar and its results are conditionally rendered inside a single div:
  ```jsx
  <div className={searchActive ? 'categorySearchContainer showElement' : 'categorySearchContainer hideElement'}>
    <input className="categorySearchInput" .../>
    // either:
    // - a mapped list of <p className="addListItem"> (dropdown options), OR
    // - a message & "Add New" button
    <div className="searchFullBackground" onClick={...}></div>
  </div>
  ```
- The dropdown list is inline in the container, not separately layered. This is why it scrolls out of view.

### CSS (`page.css`)

- `.categorySearchContainer:has(> input[type="text"])` is currently:
  - `position: relative;`
  - `max-height: 250px;`
  - `overflow: scroll;`
  - Scrollbars are `visibility: hidden;`
- List items `.addListItem` have basic hover and spacing styles.

---

# Final Implementation Plan

## 1. Refactor the JSX in AddCategory.tsx

- **Structure:**  
  - Wrap input in a relative parent.
  - Move the search results dropdown into a new `<div class="category-dropdown-list">` that is absolutely positioned below the input.
  - Only render the dropdown-list div if search is active and query is not empty.

- **Backdrop/Focus:**  
  - Retain the full-screen `.searchFullBackground` for closing on outside click.

## 2. CSS Changes

- **Dropdown List (`.category-dropdown-list`):**
  - `position: absolute`, `left: 0`, `top: 100%`, `width: 100%` (anchored below input)
  - `background: white`, box-shadow, border, rounded corners.
  - `z-index: 999;`
  - `max-height: 200px;`
  - `overflow-y: auto;`
- **Scrollbar Styling (cute and visible):**
  - `::-webkit-scrollbar`, `::-webkit-scrollbar-thumb` for webkit
  - `scrollbar-width: thin; scrollbar-color:` for Firefox, matching the UI palette.
- **Remove `overflow` and scrollbar styles from `.categorySearchContainer`** (move these to the dropdown list).
- Make sure `.categorySearchContainer` is only `position: relative;` and `z-index` as needed.

## 3. Integration

- Edge cases: Clicking a dropdown item or backdrop should always close search.
- The dropdown remains visually anchored even as the parent scrolls.

# Required Code Changes

## A. `AddCategory.tsx` - Outline

```tsx
<div className="categorySearchWrapper" style={{ position: "relative" }}>
  <input ... />
  {searchActive && searchQuery && (
    <div className="category-dropdown-list">
      {filteredList.length > 0 ? (
        filteredList.map(...)
      ) : (
        <div>
          <p>...</p>
          <div className="addCategoryButton" onClick={buildNewCategory}>Add New</div>
        </div>
      )}
    </div>
  )}
  <div className="searchFullBackground" ... />
</div>
```
- Remove scroll/overflow from `.categorySearchContainer`.
- Put all dropdown options in `.category-dropdown-list`.

## B. `page.css` - Outline

```css
.categorySearchWrapper {
  position: relative;
  width: 100%; /* or fixed width if needed */
}

.category-dropdown-list {
  position: absolute;
  left: 0;
  top: 105%; /* or top: 100% plus some margin */
  width: 100%;
  background: #fff;
  border: 2px solid #323232;
  border-radius: 15px;
  z-index: 999;
  max-height: 200px;
  overflow-y: auto;
  box-shadow: 2px 6px 18px 0px #e1e4ea;
  /* Custom scrollbar, see below */
}

/* Custom scrollbar: */
.category-dropdown-list::-webkit-scrollbar {
  width: 8px;
}

.category-dropdown-list::-webkit-scrollbar-thumb {
  background: #d7e8fb;
  border-radius: 8px;
  border: 2px solid #fff;
}
.category-dropdown-list::-webkit-scrollbar-track {
  background: #fff;
}

.category-dropdown-list {
  scrollbar-width: thin;
  scrollbar-color: #d7e8fb #fff;
}
```
